### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by ismaelrivas** [jnimmo/hass-intesisbox#1]
My HVAC doesn't support swings, although intesisbox says yes, so I changed line **95** from **climate.py** _`self._swing_list = [SWING_LIST_STOP]`_ by _`self._swing_list = False`_

Also, I changed the line **223** of **climate.py** _`self._fan_speed = self._controller.fan_speed.title()`_ by _`self._fan_speed = self._controller._fan_speed_list`_ since `fan_speed.title()` doesn't exist in **intesisbox.py**

With these two, finally, the entity is created in hass, but the connection with intesisbox is lost, you can see in the log message **"Lost connection to IntesisHome."**

Thanks for the work.

**Comment by jnimmo** [comment]
I've just pushed an updated climate.py and intesisbox.py, are you able to try those,
also add
```yaml

logger:
  logs:
    pyintesisbox: debug
```
to your configuration.yaml

Then if you could send a copy of your Home Assistant log (or at least any lines containing 'pyintesisbox'- it should log all data received from the unit which might help me understand why the connection is lost

**Comment by ismaelrivas** [comment]
Thanks for answering.

I was wrong, the component does not lose the connection What happens is that you need to add "\r" to send the message on line **208** of **intesisbox.py** _`message = "SET,{}:{},{}\r".format(1, uid, value)`_

Well, now it responds when I change the operations mode, but in the hass interface the change is not shown immediately, for example, I have to press the cold mode a second time to be displayed in the interface (at the first press my HVAC is turned on and put in cold mode). And the same thing happens when I turn it off or put it in fan mode.

If I do not click a second time, after a few minutes the interface updates itself and shows the correct mode.


One more thing, when I put it in fan mode it appears in the hass interface that the target temperature is 3276.8

Attachment logg
[intesis2.log](https://github.com/jnimmo/hass-intesisbox/files/3149565/intesis2.log)

**Comment by jnimmo** [comment]
Sorry, I forgot to push the changes to Github I made the other day. The version up there now should include more debugging (the received data from Intesisbox too).
Good spotting with the \r, I've fixed that now. 
The 32768 is a null value used by Intesis so I've put in some handling for that, could you try the latest version of the code now?

When you say about the mode change not showing immediately, is that if you have changed the mode using the remote, or changed the mode through Home Assistant?
Cheers

**Comment by ismaelrivas** [comment]
Thanks again.

As soon as I can, I test the modifications and send the log.
The problem with mode change occurs when I use the Home Assistan to change
the mode and when I use the remote.

**Comment by jnimmo** [comment]
Assume this is fixed as haven't heard back, but please re-open if not!
