### ISSUE TITLE
Issues with model: INWMPUNI001I000

### ISSUE THREAD

**Issue by zuhair68** [jnimmo/hass-intesisbox#13]
I'm using this model: [INWMPUNI001I000](https://www.intesis.com/products/ac-interfaces/wifi-gateways/universal-ascii-wifi-ac-is-ir-wmp-1?ordercode=INWMPUNI001I000)

**Issues**: 
- It become unavailable when turned on.
- HA is not showing the correct status of HVAC (Cool, OFF ... etc)

**Update: when changing the HVAC status to FAN then back to COOL, it works fine**

**Working fine:**
- Showing the correct temperature 
- Although it's not showing the HVAC status, the AC is responding to OFF/ON and changing the set temperature

**Comment by reesion** [comment]
Hi,

I can confirm this behaviour as it is happening to me as well.

**Comment by jnimmo** [comment]
Currently undergoing a complete re-write, so expect any issues like this to be resolved shortly :)

**Comment by jbergler** [comment]
@zuhair68 the latest version of the extension (v1.0.0) has a bunch of additional debug logging to help us fix problems  like this. Could you configure the following in your config and share logs that match `intesisbox` in this ticket please?
```
logger:
  default: info
  logs:
    custom_components.intesisbox: debug
```
