### ISSUE TITLE
Still maintained in 2021?

### ISSUE THREAD

**Issue by joaomoreira-obvio** [jnimmo/hass-intesisbox#15]
Hello,
I'm considering to buy a WMP gateway from Intesis (Daikin).
I would like to know to current state of this project, is everything working fine?
It is still maintained? It would be very useful a section on README about the current project state.
Many thanks

**Comment by joaomoreira-obvio** [comment]
I'll going that route, many thanks, you have one more tester 😎

**Comment by AAlmarwani93** [comment]
Hello I currently have an intesis WMP universal IR. I would like to tell you that everything works well and the integration is great. Sometimes though when you set the mode to cool it produces state unknown yet if you switch to fan then to cool it will regain the state. is that something expected ?

**Comment by luke-barnett** [comment]
@jnimmo what's left to get this into home assistant core?

**Comment by jnimmo** [comment]
Hey Luke - it needs some unit tests written for Config Flow as apparently integrations aren't allowed to make changes to their YAML configuration schemas anymore (https://github.com/home-assistant/core/pull/57883). I have Config Flow all working on this other branch (https://github.com/jnimmo/home-assistant/tree/intesishome-config-flow) however need tests written for it, and unfortunately don't have capacity to work on this at the moment, so if anyone else has interest and capacity, that would be greatly appreciated!
