### ISSUE TITLE
Not working anymore since latest HA update 2023.3.6

### ISSUE THREAD

**Issue by Makestudio20** [jnimmo/hass-intesisbox#29]
Hi,

I enjoyed this plugin and it was working correctly, but since the latest HA update the plugin doesn't seem to work anymore. 
It hangs and says 'initialising' when adding a host (IP address). Even an uninstall and complete reinstall doesn't seem to do the trick.

Anyone else experiencing the same issues?
In the log I do see this (it should add a connection to 192.168.3.51 which is the Intesis module -it's online and worked before with the exact same settings):

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: 11:06:06 (2 occurrences)
Last logged: 11:07:37

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.3.51', 3310)

**Comment by Makestudio20** [comment]
Logger: homeassistant.components.climate
Source: runner.py:179
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 11:06:13 (1 occurrences)
Last logged: 11:06:13

Setup of climate platform intesisbox is taking over 10 seconds.

**Comment by jbergler** [comment]
@Makestudio20 could you enable some additional logging and share those?
```
logger:
  logs:
    custom_components.intesisbox: debug
    pyintesisbox: debug
```

**Comment by jbergler** [comment]
Little bit more detail, I've upgraded my install to 2023.3.6 and have no issues.
I've added some additional logging in the latest version of the component, but I don't think this will be very helpful if the connection isn't even establishing.

Could you confirm that the device is responding on that port (even just with telnet or nc to check if you can connect)

**Comment by jbergler** [comment]
I merged what I think might be a fix for this separately to the above PR, via https://github.com/jnimmo/hass-intesisbox/pull/33

Let me know if the issue has been resolved in the latest update.

**Comment by Makestudio20** [comment]
Thanks! This one can be closed. Appears it was more of an issue with the device itself not connecting properly. After a complete reinstall of everything and adding each device separately again it appears to have been fixed.
