### ISSUE TITLE
Platform not found in HA 0.96 or higher

### ISSUE THREAD

**Issue by colinator19** [jnimmo/hass-intesisbox#3]
The platform does not seem to load in Home Assistant 0.96 or higher.
I have placed the files in the intesisbox folder from the repo in the “custom_components/intesisbox” folder and added the below to the config:
```
- platform: intesisbox
  host: 192.168.0.5
```
yet when validating the config I get the invalid config error: 
**Platform not found: climate.intesisbox**

Any idea what is needed to fix this issue?

**Comment by tinglis1** [comment]
To use this with the 0.95 or above the component needs to be updated to conform to the new climate platform requirements. At the moment I am still running 0.94.4 as this supports this component.

**Comment by tinglis1** [comment]
I have updated the integration and am testing it on my system. I will try get it uploaded/merged over the coming week.

**Comment by tinglis1** [comment]
I have made a pull request for this fix.
You can find my version here --> https://github.com/tinglis1/hass-intesisbox.
and my pull request here --> https://github.com/jnimmo/hass-intesisbox/pull/4

**Comment by tinglis1** [comment]
Anyone had a chance to test the updates for the new platform?
So far it has been working for me.

**Comment by jnimmo** [comment]
Merged the changes, thanks for that
