### ISSUE TITLE
cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing'

### ISSUE THREAD

**Issue by feuerradder** [jnimmo/hass-intesisbox#42]
Hi!

After updating to the latest HA version i get this error when i try to config the integration at the configuration.yaml:

`Platform error climate.intesisbox - cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)`

I'm not sure how to proceed. Any advice or solution?

**Comment by warwickofthegh** [comment]
Are you just setting up new? I had an existing setup and the ConfigEntry error is kind of similar to the issues I've just raised also.

**Comment by feuerradder** [comment]
> Are you just setting up new? I had an existing setup and the ConfigEntry error is kind of similar to the issues I've just raised also.

It's an existing installation. I updated HA, then the intesisbox integration stop working because it cant connect to the device. I updated the files with the 2.0 version and get the error above

I think ConfigEntry from homeassistant.helpers.typing library no longer exists or something similar. This code is on the climate.py file. But i'm not soy confidence editing python scripts to try to fix the code

**Comment by warwickofthegh** [comment]
Would recommend adding a custom repo via HACS, using this repo url and installing via that method rather than manual copy into custom_components - fixed my issue around this error.

**Comment by feuerradder** [comment]
> Would recommend adding a custom repo via HACS, using this repo url and installing via that method rather than manual copy into custom_components - fixed my issue around this error.

I didnt try this solution and it works great!

Thanks for your response!
