### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by joaomoreira-obvio** [jnimmo/hass-intesisbox#49]
Unable to prepare setup for platform intesisbox.climate: Platform not found (cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py))

Currently on Home Assistant OS 10.4
Core 2023.8.1

Can you please take a look?
Thank you very much

**Comment by Glirido** [comment]
I think its a duplicate of #47
