### ISSUE TITLE
Errors Message in Home Assistant Logs (Deprecation)

### ISSUE THREAD

**Issue by fonzy69** [jnimmo/hass-intesisbox#53]
Hi, 
there is messages in HA logs: 

> Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 06:46:08 (1 occurrences)
Last logged: 06:46:08
TEMP_CELSIUS was used from intesisbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues>

>Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Thermostat (documentation, issues)
First occurred: 06:46:08 (9 occurrences)
Last logged: 06:46:08
HVAC_MODE_HEAT was used from intesisbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues
HVAC_MODE_OFF was used from intesisbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues
SUPPORT_FAN_MODE was used from intesisbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues
SUPPORT_SWING_MODE was used from intesisbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues
SUPPORT_TARGET_TEMPERATURE was used from intesisbox, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues>

>Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1567
First occurred: 06:46:40 (1 occurrences)
Last logged: 06:46:40
Entity None (<class 'custom_components.intesisbox.climate.IntesisBoxAC'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE: 9>, please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation>

there is also another message wich is not about deprecation : 

>Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Thermostat (documentation, issues)
First occurred: 06:46:40 (3 occurrences)
Last logged: 06:46:40
Entity None (<class 'custom_components.intesisbox.climate.IntesisBoxAC'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues
Entity None (<class 'custom_components.intesisbox.climate.IntesisBoxAC'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues
Entity None (<class 'custom_components.intesisbox.climate.IntesisBoxAC'>) implements HVACMode(s): off, heat_cool, heat, dry, fan_only, cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jnimmo/hass-intesisbox/issues>

Thanks for your work
Best Regards

**Comment by luismalddonado** [comment]
In version [v2.0.1] this should be fixed now
