### ISSUE TITLE
Looping "Opening connection to IntesisBox" causing CLOSE:MAXCONN disconnections

### ISSUE THREAD

**Issue by CV8R** [jnimmo/hass-intesisbox#54]
Whilst trying to determine the cause of is "taking over 10 seconds" and ignored commands I found that all 3 of my IntesisBox integrations try to make a new connect and then the connection is dropped by the IntesisBox because of what looks like too many open connections. The process continually repeats.

I have one IntesisBox that eventually stops accepting connections on port 3310 until powered off and rebooted -  it looks like this is likely the trigger.

Logs:
[IntesisBoxLog.txt](https://github.com/jnimmo/hass-intesisbox/files/14419042/IntesisBoxLog.txt)

**Comment by luismalddonado** [comment]
I have the same issue. Sometime, when I start/stop the HA Intesisbox integration several times, the Intesisbox  becomes unaccesible and I have to restart it.

**Comment by CV8R** [comment]
I think I may have this Multiple connections issue resolved now.

I needed to remove the intesisbox entries from the configuration.yaml and only configure them from the GUI Integrations Page.

Removed:
```
climate:
  - platform: intesisbox
    host: <IP Address>
```

To be sure I deleted the configuration.yaml entries and deleted the integration entries then restarted HA.  I then added them back in from the GUI in the Integrations.

**Comment by jedney** [comment]
Same multi-connection leading to IntesisBox reboot issue here. I also had the legacy configuration.yaml entries. I've removed those and re-setup the integration. Will continue to monitor - I owe you a beer CV8R if that's the solution! :-)

**Comment by luismalddonado** [comment]
README has ben updated in v2.0.1.

**Comment by CV8R** [comment]
Fixed by removing deleting the intesisbox configuration.yaml entries and configuring in GUI.
