### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by autumnwalker** [jnimmo/hass-intesisbox#8]
Looking at buying a new Intesisbox for my Fujitsu system.

Happy to jump in and test, etc. but I'm not a developer and wouldn't know where to begin to try and integrate / re-integrate the intesis / HMS box into Home Assistant.

**Comment by jnimmo** [comment]
The HMP spec is unlikely to change anytime soon so it's only really the Home Assistant interface which needs to be updated as they change things which would usually be pretty minor. There are a couple of things I need to make time to fix some warnings but as far as I know it's still working :)

**Comment by autumnwalker** [comment]
Thanks @jnimmo!

**Comment by tinglis1** [comment]
I can confirm that it is working and has only needed updates to the HA side of the integration.
There is room for improvement but it is functional.
