### ISSUE TITLE
Platform error climate.intesisbox - No module named 'config.custom_components' after upgrade to b7c7d52

### ISSUE THREAD

**Issue by sbik38** [jnimmo/hass-intesisbox#9]
Hello HACS aleterted me that an updatre was available for Intesisbox Integration (version b7c7d52) . I applied it, but when I check my configuration.yaml file, the system report me the below error : 
Platform error climate.intesisbox - No module named 'config.custom_components' 

Everything was working fine before that update
Here is the Climate section of my YAML file : 

- platform: intesisbox
  host: 192.168.0.39

Any idea how to solve this ?

Thanks

**Comment by jnimmo** [comment]
Apologies didn't realise that would cause HACS to push out an update, I'll have to learn how to avoid that in future (I suppose a dev branch) - try the version I've just pushed now and see how you go

**Comment by sbik38** [comment]
Thanks a lot jnimmo. it work again. Perfect
Btw, which news feature did you add in that new version ?

**Comment by jnimmo** [comment]
Glad to hear, thanks for that. No new features, just made the connection code hopefully a little more reliable. Will be interested to hear your feedback about stability

**Comment by sbik38** [comment]
ok will keep you informed...

**Comment by sbik38** [comment]
Hi
Since the last update + download of latest code you provided me, I can see in HA my Climate.Intesibox device, but it State is "unavailable". Any idea of root cause ? Everything was working fine before that update. I checkd to ping my intesisbox and it reply properly
![image](https://user-images.githubusercontent.com/60422995/115443619-c4841180-a213-11eb-97c9-e11ee857a461.png)

**Comment by jnimmo** [comment]
Do you mean it always shows unavailable or after a time it shows unavailable?
That means it thinks it isn't connected to the device and I would need to see logging from it to understand why, to see any alerts about disconnects

**Comment by sbik38** [comment]
Yes since the updatye I always get "unavailable"
Here is the log :

Logger: homeassistant.helpers.service
Source: helpers/service.py:127
First occurred: 9:11:11 PM (3 occurrences)
Last logged: 9:11:12 PM
Unable to find referenced entities climate.intesisbox

**Comment by sbik38** [comment]
Hi Jnimmo,

Do you have any idea of possible root cause based on my Log ?
Thanks

**Comment by jnimmo** [comment]
Not really sorry, it could be thinking it's disconnected when it's not, or I'd need the more detailed logging - https://www.home-assistant.io/integrations/logger/ enabled for custom_components.intesisbox at debug level to see if it was connected or not

**Comment by sbik38** [comment]
Hi,

Here is below all the log I got in DEBUG mode (in Chronological sort) : 

Logger: homeassistant.components.climate
Source: /usr/local/lib/python3.8/asyncio/events.py:81
Integration: Climate (documentation, issues)
First occurred: 9:39:13 PM (1 occurrences)
Last logged: 9:39:13 PM
Setup of climate platform intesisbox is taking over 10 seconds.

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:237
Integration: Climate (documentation, issues)
First occurred: 9:40:03 PM (1 occurrences)
Last logged: 9:40:03 PM
Setup of platform intesisbox is taking longer than 60 seconds. Startup will proceed without waiting any longer.

Logger: pyintesisbox
Source: custom_components/intesisbox/intesisbox.py:94
First occurred: 9:41:03 PM (1 occurrences)
Last logged: 9:41:03 PM
Lost connection to Intesisbox 192.168.0.39. Exception: 0 bytes read on a total of undefined expected bytes

Logger: homeassistant.helpers.service
Source: helpers/service.py:127
First occurred: 10:31:42 PM (1 occurrences)
Last logged: 10:31:42 PM
Unable to find referenced entities climate.intesisbox

If you have any idea how to solve, it's more than welcome :-)

Thanks

regards

**Comment by sbik38** [comment]
Hi Jnimmo

I updated yesterday to 2015.5 Core version, and the behavior is now a little bit different
When I restard HA, the Intesisbox data seems to be available but few time after, the access is agaon not working
Here is what I found in the log actually 👍 
This error originated from a custom integration.
Hope this helps to udnerstand what happen there
Thanks for your support

Logger: pyintesisbox
Source: custom_components/intesisbox/intesisbox.py:94
Integration: intesisbox (documentation, issues)
First occurred: 7:08:54 AM (3 occurrences)
Last logged: 7:19:18 AM

Lost connection to Intesisbox 192.168.0.39. Exception: 0 bytes read on a total of undefined expected bytes
Lost connection to Intesisbox 192.168.0.39. Exception: [Errno 104] Connection reset by peer

**Comment by jnimmo** [comment]
I've reverted the code to the previous working version in the meantime as it's a bit difficult to debug without a device to play with myself!

**Comment by sbik38** [comment]
Hi,
Just installed your reverted version and everything is working fine again.
I don"t know why, but I got a new clilmate entity created automatically with "_2" behind, but no problem, I deleted the previous Climate.entity and used that new one instead
Thank you

**Comment by jnimmo** [comment]
I've just purchased an Intesis box second hand so I'll finally be able to test it out in future!

**Comment by sbik38** [comment]
Great
If you need my support also for any test on mine, feel free to ask
